### ISSUE TITLE
Receiver glitching in certain areas

### ISSUE THREAD

**Issue by GalaxyByne** [Gibatron/analog#11]
Hello!

I've noticed that in an area of my server, receivers just bug out and glitch the audio (like interrupting). If I go anywhere else in my world, they work just fine. I've yet to measure how big this area is. If you need anymore info, i'm up to providing.

Thanks!

**Comment by Gibatron** [comment]
That's strange, I'd be inclined to believe it's a performance issue with something in that area. Due to the way Analog works, if the server is lagging the audio will suffer. Is there anything in said area that could be creating lag for the server?
You could use [Spark](https://modrinth.com/mod/spark) to profile the server to see if anything else is affecting it.

**Comment by GalaxyByne** [comment]
I'm very sorry, I actually apologize as I am actually unable to recreate the issue. The next day it was gone. If I find another spot I'll make sure to investigate more.
